apiVersion: v2
appVersion: "1.9"
description: Mailu mail system
name: mailu
version: 0.3.3
icon: https://mailu.io/master/_images/logo.png
dependencies:
  - name: postgresql
    version: 11.9.*
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 11.3.*
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
