---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-admin" (include "mailu.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: admin
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  {{- if .Values.admin.updateStrategy }}
  strategy: {{- toYaml .Values.admin.updateStrategy | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.admin.revisionHistoryLimit }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: admin
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: admin
        {{- if .Values.admin.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.admin.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.admin.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.admin.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "common.images.pullSecrets" (dict "images" (list .Values.admin.image) "global" .Values.global) | nindent 6 }}
      {{- if .Values.admin.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.admin.hostAliases "context" $) | nindent 8 }}
      {{- end }}    
      {{- if .Values.admin.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.admin.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.admin.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.admin.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.priorityClassName }}
      priorityClassName: {{ .Values.admin.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.admin.schedulerName }}
      schedulerName: {{ .Values.admin.schedulerName | quote }}
      {{- end }}
      {{- if .Values.admin.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.admin.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.admin.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.admin.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.admin.initContainers }}
      initContainers: {{- include "common.tplvalues.render" (dict "value" .Values.admin.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: admin
          image: {{ .Values.admin.image.repository }}:{{ default .Values.mailuVersion .Values.admin.image.tag }}
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          volumeMounts:
            - name: data
              subPath: admin
              mountPath: /data
            - name: data
              mountPath: /dkim
              subPath: dkim
            {{- if .Values.admin.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.admin.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
          env:
            - name: LOG_LEVEL
              value: {{ default .Values.logLevel .Values.admin.logLevel }}
            - name: QUOTA_STORAGE_URL
              value: redis://{{ include "mailu.fullname" . }}-redis/1
            - name: RATELIMIT_STORAGE_URL
              value: redis://{{ include "mailu.fullname" . }}-redis/2
            - name: POSTMASTER
              value: {{ default "postmaster" .Values.postmaster }}
            - name: DOMAIN
              value: "{{ required "'domain' needs to be set" .Values.domain }}"
            - name: HOSTNAMES
              value: "{{ join "," .Values.hostnames }}"
            - name: IMAP_ADDRESS
              value: {{ include "mailu.hosts.dovecot" . }}
            - name: POP3_ADDRESS
              value: {{ include "mailu.hosts.dovecot" . }}
            - name: SMTP_ADDRESS
              value: {{ include "mailu.hosts.postfix" . }}
            - name: AUTHSMTP_ADDRESS
              value: {{ include "mailu.hosts.postfix" . }}
            - name: REDIS_ADDRESS
              value: {{ include "mailu.hosts.redis" . }}
            {{- if .Values.roundcube.enabled }}
            - name: WEBMAIL
              value: roundcube
            - name: WEB_WEBMAIL
              value: {{ required "roundcube.uri" .Values.roundcube.uri }}
            - name: WEBMAIL_ADDRESS
              value: {{ include "mailu.fullname" . }}-roundcube.{{ .Release.Namespace }}.svc.{{ include "mailu.clusterDomain" . }}
            {{- else }}
            - name: WEBMAIL
              value: none
            - name: WEBMAIL_ADDRESS
              value: localhost
            - name: WEB_WEBMAIL
              value: /
            {{- end }}
            - name: FRONT_ADDRESS
              value: {{ include "mailu.fullname" . }}-front.{{ .Release.Namespace }}
            - name: RECIPIENT_DELIMITER
              value: +
            - name: SUBNET
              value: {{ .Values.subnet }}
            - name: PASSWORD_SCHEME
              value: "{{ default "PBKDF2" .Values.passwordScheme }}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "mailu.secretName" . }}
                  key: secret-key
            - name: MESSAGE_RATELIMIT
              value: "{{ required "mail.messageRatelimit" .Values.mail.messageRatelimit }}"
            - name: MESSAGE_RATELIMIT_EXEMPTION
              value: "{{ default "" .Values.mail.messageRatelimitExemption }}"
            - name: AUTH_RATELIMIT_IP
              value: "{{ required "mail.authRatelimitIP" .Values.mail.authRatelimitIP }}"
            - name: AUTH_RATELIMIT_IP_V4_MASK
              value: "{{ required "mail.authRatelimitIPv4Mask" .Values.mail.authRatelimitIPv4Mask }}"
            - name: AUTH_RATELIMIT_IP_V6_MASK
              value: "{{ required "mail.authRatelimitIPv6Mask" .Values.mail.authRatelimitIPv6Mask }}"
            - name: AUTH_RATELIMIT_USER
              value: "{{ required "mail.authRatelimitUser" .Values.mail.authRatelimitUser }}"
            - name: AUTH_RATELIMIT_EXEMPTION_LENGTH
              value: "{{ required "mail.authRatelimitExemtionLength" .Values.mail.authRatelimitExemtionLength }}"
            - name: AUTH_RATELIMIT_EXEMPTION
              value: "{{ default "" .Values.mail.authRatelimitExemtion }}"
            {{- if .Values.initialAccount }}
            - name: INITIAL_ADMIN_ACCOUNT
              value: {{ required "'initialAccount.username' needs to be set if 'initialAccount' is used." .Values.initialAccount.username }}
            - name: INITIAL_ADMIN_DOMAIN
              value: {{ required "'initialAccount.domain' needs to be set if 'initialAccount' is used." .Values.initialAccount.domain }}
            - name: INITIAL_ADMIN_PW
              valueFrom:
                secretKeyRef:
                  name: {{ template "mailu.initialAccount.secretName" . }}
                  key: initial-account-password
            {{- end }}
            {{- if eq .Values.database.type "sqlite" }}
            - name: DB_FLAVOR
              value: sqlite
            {{- else if .Values.mariadb.enabled }}
            - name: DB_FLAVOR
              value: mysql
            - name: DB_USER
              value: {{ required "mariadb.auth.username is required when mariadb.enabled is true" .Values.mariadb.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.secretName" .Subcharts.mariadb }}
                  key: mariadb-password
            - name: DB_HOST
              value: {{ template "mariadb.primary.fullname" .Subcharts.mariadb }}
            - name: DB_NAME
              value: {{ .Values.mariadb.auth.database | quote }}
            {{- else if .Values.postgres.enabled }}
            - name: DB_FLAVOR
              value: postgres
            - name: DB_USER
              value: {{ required "postgresql.auth.username is required when postgresql.enabled is true" .Values.postgresql.auth.username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secretName" .Subcharts.postgresql }}
                  key: {{ include "postgresql.userPasswordKey" .Subcharts.postgresql }}
            - name: DB_HOST
              value: {{ template "mariadb.primary.fullname" .Subcharts.mariadb }}
            - name: DB_NAME
              value: {{ include "postgresql.database" .Subcharts.postgresql }}
            {{- else if eq .Values.database.type "mysql" }}
            - name: DB_FLAVOR
              value: mysql
            - name: DB_USER
              value: {{ required "database.mysql.user" .Values.database.mysql.user }}
            - name: DB_PW
              value: {{ required "database.mysql.password" .Values.database.mysql.password }}
            - name: DB_NAME
              value: {{ required "database.mysql.database" .Values.database.mysql.database }}
            - name: DB_HOST
              {{- if .Values.database.mysql.host }}
              value: {{ .Values.database.mysql.host }}
              {{- else }}
              value: {{ include "mailu.fullname" . }}-mysql
              {{- end }}
            {{- else if eq .Values.database.type "postgresql" }}
            - name: DB_FLAVOR
              value: postgresql
            - name: DB_USER
              value: {{ required "database.postgresql.user" .Values.database.postgresql.user }}
            - name: DB_PW
              value: {{ required "database.postgresql.password" .Values.database.postgresql.password }}
            - name: DB_NAME
              value: {{ required "database.postgresql.database" .Values.database.postgresql.database }}
            - name: DB_HOST
              {{- if .Values.database.postgresql.host }}
              value: {{ .Values.database.postgresql.host }}
              {{- end }}
            {{- else }}
            value: {{ required "database.type must be one of sqlite/mysql/postgresql" .None }}
            {{- end }}
            {{- if .Values.timezone }}
            - name: TZ
              value: {{ .Values.timezone }}
            {{- end }}
            {{- if .Values.admin.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.admin.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.admin.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.admin.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.admin.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.admin.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.admin.resources }}
          resources: {{- toYaml .Values.admin.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.admin.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.admin.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /sso/login
              port: http
          {{- end }}
          {{- if .Values.admin.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.admin.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /sso/login
              port: http
          {{- end }}
          {{- if .Values.admin.readinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.admin.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /sso/login
              port: http
          {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{- include "mailu.admin.claimName" . }}


