---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-admin" (include "mailu.fullname" .) }}
  namespace: {{ include "mailu.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: admin
  {{- if .Values.admin.service.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.admin.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector: {{- include "mailu.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  ports:
  - name: http
    port: 80
    protocol: TCP