config: .trivy.yaml
debug: true
exit-code: 1
ignorefile: .trivyignore
misconfiguration:
  helm:
    set:
      - ./mailu/
    values:
      - ./mailu/ci/helm-lint-values.yaml
severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
