hostnames:
  - example.com

domain: example.com

initialAccount:
  enabled: true
  username: mailadmin
  domain: mydomain.com
  password: chang3m3!

secretKey: chang3m3!

persistence:
  single_pvc: false

postgresql:
  enabled: true
  postgresqlUsername: mailu
  postgresqlPassword: chang3m3!
  postgresqlDatabase: mailu
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 1

ingress:
  enabled: true
  selfSigned: true
  annotations:
    auth.cluster.arpa/enabled: "false"

front:
  logLevel: WARNING
#  image:
#    tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m

admin:
  logLevel: WARNING
#  image:
#    tag: master
  resources:
    requests:
      memory: 500Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 1

postfix:
  logLevel: WARNING
#  image:
#    tag: master
  resources:
    requests:
      memory: 2Gi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 1

dovecot:
  logLevel: WARNING
#  image:
#    tag: master
  resources:
    requests:
      memory: 500Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 1

rspamd:
  logLevel: INFO
#  image:
#    tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 1

clamav:
  logLevel: WARNING
#  image:
#    tag: master
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 1

roundcube:
  logLevel: WARNING
#  image:
#    tag: master
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 1

webdav:
  logLevel: WARNING
#  image:
#    tag: master

fetchmail:
  logLevel: WARNING
#  image:
#    tag: master

redis:
  master:
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 1
