---
{{- if .Values.clamav.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-clamav" (include "mailu.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: clamav
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  {{- if .Values.clamav.updateStrategy }}
  strategy: {{- toYaml .Values.clamav.updateStrategy | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.clamav.revisionHistoryLimit }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: clamav
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: clamav
        {{- if .Values.clamav.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.clamav.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.clamav.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.clamav.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "common.images.pullSecrets" (dict "images" (list .Values.clamav.image) "global" .Values.global) | nindent 6 }}
      {{- if .Values.clamav.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.priorityClassName }}
      priorityClassName: {{ .Values.clamav.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.clamav.schedulerName }}
      schedulerName: {{ .Values.clamav.schedulerName | quote }}
      {{- end }}
      {{- if .Values.clamav.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.clamav.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.clamav.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.clamav.initContainers }}
      initContainers: {{- include "common.tplvalues.render" (dict "value" .Values.clamav.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: clamav
          image: {{ .Values.clamav.image.repository }}:{{ default .Values.mailuVersion .Values.clamav.image.tag }}
          imagePullPolicy: {{ .Values.clamav.image.pullPolicy }}
          volumeMounts:
            - name: data
              subPath: clamav
              mountPath: /data
            {{- if .Values.clamav.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.clamav.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
          env:
            - name: LOG_LEVEL
              value: {{ default .Values.logLevel .Values.clamav.logLevel }}
            {{- if .Values.timezone }}
            - name: TZ
              value: {{ .Values.timezone }}
            {{- end }}
            {{- if .Values.clamav.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.clamav.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.clamav.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.clamav.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.clamav.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.clamav.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - name: clamav
              containerPort: 3310
              protocol: TCP
          {{- if .Values.clamav.resources }}
          resources: {{- toYaml .Values.clamav.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.clamav.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.clamav.startupProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command: ["echo", "PING", "|", "nc", "localhost", "3310", "|", "grep", "PONG"]
          {{- end }}
          {{- if .Values.clamav.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.clamav.livenessProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command: ["echo", "PING", "|", "nc", "localhost", "3310", "|", "grep", "PONG"]
          {{- end }}
          {{- if .Values.clamav.readinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.clamav.readinessProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command: ["echo", "PING", "|", "nc", "localhost", "3310", "|", "grep", "PONG"]
          {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mailu.clamav.claimName" . }}
{{- end }}
