---
{{- if and (.Values.roundcube.enabled) (not .Values.persistence.single_pvc) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mailu.roundcube.claimName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: roundcube
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.roundcube.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.roundcube.persistence.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.roundcube.persistence.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.roundcube.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.roundcube.persistence.size | quote }}
  {{- if .Values.roundcube.persistence.storageClass }}
  storageClassName: {{ .Values.roundcube.persistence.storageClass }}
  {{- end }}
{{- end }}
