---
{{- if not .Values.global.database.roundcube.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailu.database.roundcube.secretName" . }}
type: Opaque
data:
  {{ include "mailu.database.roundcube.secretKey" . -}}: {{ (include "mailu.database.roundcube.password" . ) }}
{{- end }}
