# This file is derived from https://github.com/Mailu/Mailu/blob/master/docs/kubernetes/mailu/redis.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailu.fullname" . }}-redis
spec:
  selector:
    matchLabels:
      app: {{ include "mailu.fullname" . }}
      component: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "mailu.fullname" . }}
        component: redis
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: redis
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: Always
        volumeMounts:
          - name: data
            subPath: redis
            mountPath: /data
          {{- if .Values.timezone }}
          - name: zoneinfo
            mountPath: /usr/share/zoneinfo
            readOnly: true
          - name: zoneinfo
            subPath: {{ .Values.timezone }}
            mountPath: /etc/localtime
            readOnly: true
          {{- end }}
        ports:
          - containerPort: 6379
            name: redis
            protocol: TCP
        {{- with .Values.redis.resources }}
        resources:
        {{- .|toYaml|nindent 10}}
        {{- end }}
        {{- if .Values.redis.startupProbe}}
        startupProbe:
          exec:
            command:
              - /usr/local/bin/redis-cli
              - info
              - status
          periodSeconds:  {{ default 10 .Values.redis.startupProbe.periodSeconds }} 
          failureThreshold: {{ default 30 .Values.redis.startupProbe.failureThreshold }} 
          timeoutSeconds: {{ default 5 .Values.redis.startupProbe.timeoutSeconds }} 
        {{- end }}
        {{- if .Values.redis.livenessProbe}}
        livenessProbe:
          exec:
            command:
              - /usr/local/bin/redis-cli
              - info
              - status
          periodSeconds:  {{ default 10 .Values.redis.livenessProbe.periodSeconds }} 
          failureThreshold: {{ default 3 .Values.redis.livenessProbe.failureThreshold }} 
          timeoutSeconds: {{ default 5 .Values.redis.livenessProbe.timeoutSeconds }} 
        {{- end }}
        {{- if .Values.redis.readinessProbe}}
        readinessProbe:
          exec:
            command:
              - /usr/local/bin/redis-cli
              - info
              - status
          periodSeconds:  {{ default 10 .Values.redis.readinessProbe.periodSeconds }} 
          failureThreshold: {{ default 1 .Values.redis.readinessProbe.failureThreshold }} 
          timeoutSeconds: {{ default 5 .Values.redis.readinessProbe.timeoutSeconds }} 
        {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mailu.claimName" . }}
        {{- if .Values.timezone }}
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
            type: Directory
        {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.fullname" . }}-redis
  labels:
    app: {{ include "mailu.fullname" . }}
    component: redis
spec:
  selector:
    app: {{ include "mailu.fullname" . }}
    component: redis
  ports:
  - name: redis
    port: 6379
    protocol: TCP
