{{- if and (.Values.initialAccount) (not .Values.initialAccount.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailu.initialAccount.secretName" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  {{ include "mailu.initialAccount.secretKey" . -}}: {{ include "mailu.initialAccount.password" . }}
{{- end }}
