{{- if and (.Values.initialAccount) (not .Values.initialAccount.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mailu.fullname" . }}-initial-account
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  initial-account-password: {{ template "mailu.initialAccount.password" . }}
{{- end }} 