name: '[Support] Update README metadata'

on:
  pull_request_target:
    branches:
      - master
      - refactor
    paths:
      - 'mailu/values.yaml'
permissions:
  contents: write
jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bitnami-labs/readme-generator-for-helm
        uses: actions/checkout@v2
        with:
          repository: 'bitnami-labs/readme-generator-for-helm'
          ref: '1af12881436b1f58f0643d733fd5196b4a11caa8'
          path: readme-generator-for-helm

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('readme-generator-for-helm/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install readme-generator-for-helm dependencies
        run: cd readme-generator-for-helm && npm install

      - name: Checkout bitnami/charts
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          path: charts
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute readme-generator-for-helm
        run: |
          echo "Updating README.md for mailu chart"
          readme-generator-for-helm/bin/index.js --values "charts/mailu/values.yaml" --readme "charts/mailu/README.md" --schema "/tmp/schema.json"
      - name: Push changes
        run: |
          # Push all the changes
          cd charts
          git config user.name "Mailu"
          git config user.email "mailu@example.com"
          git add . && git commit -am "Update README.md with readme-generator-for-helm" --signoff && git push
