---
name: Update README metadata

on:
  # pull_request_target:
  #   branches:
  #     - master
  #   paths:
  #     - mailu/values.yaml
  workflow_dispatch:
    inputs:
      head_ref:
        description: 'Pull request head ref'
        required: true
      head_repo:
        description: 'Pull request head repo'
        required: true

permissions:
  contents: write

jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Install readme-generator-for-helm
        run: npm install -g @bitnami/readme-generator-for-helm

      - name: Checkout mailu/helm-charts
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.head_ref }}
          repository: ${{ github.event.inputs.head_repo }}
          path: charts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute readme-generator-for-helm
        run: |
          echo "Updating README.md for mailu chart"
          readme-generator --values "charts/mailu/values.yaml" --readme "charts/mailu/README.md" --schema "/tmp/schema.json"

      - name: Push changes
        run: |
          # Push all the changes
          cd charts
          git config --global user.email "actions@github.com"
          git config --global user.name "Github actions"
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -am "Update README.md with readme-generator-for-helm" --signoff
            git push
          fi
