---
name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Run helm lint
        run: helm lint --strict --values mailu/helm-lint-values.yaml mailu

      # - name: Checkout gh pages
      #   uses: actions/checkout@v2
      #   with:
      #     ref: 'gh-pages'
      #     path: gh-pages
      # - name: Pack chart
      #   run: |
      #     ./helm3 package mailu -d gh-pages
      #     ./helm3 repo index --url https://mailu.github.io/helm-charts/ gh-pages
      #     ( cd gh-pages && ./index.html.sh > index.html )
      # - name: Render chart to yamls
      #   run: |
      #     VERSION=$( grep mailu/Chart.yaml -e '^version:' | awk '{ print $2 }' )
      #     mkdir -p gh-pages/yaml
      #     rm -rf gh-pages/yaml/${VERSION}
      #     ./helm3 template mailu --values mailu/helm-lint-values.yaml --release-name mailu --namespace mailu --output-dir gh-pages/yaml/${VERSION}
      # - name: Show gh-pages changes
      #   run: |
      #     cd gh-pages
      #     git status
      # - name: Pushing changes to gh-pages
      #   run: |
      #     git config --global user.email "actions@github.com"
      #     git config --global user.name "Github actions"
      #     cd gh-pages
      #     git add .
      #     git commit -m "Automated build"
      #     git push
