on:
  release:
    types: [published]

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send message via Matrix
    steps:
    - name: Send message to mailu-helm-chart channel
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: 'matrix.org'
        token: ${{ secrets.MATRIX_TOKEN }}
        channel: '!KluZWhQwHDYrOfqJdD:make-it.fr'
        message: |
          # New release of mailu-helm-chart
          \
          Version: **${{ github.event.release.tag_name }}**\
          URL: **${{ github.event.release.html_url }}**\
          \
          Description:\
          ```${{ github.event.release.body }}```
