---
name: release-pipeline

on:
  workflow_dispatch:
    inputs:
      package:
        description: Name of the package that will be published
        required: true
        type: string
      version:
        description: Version of the package that will be published
        required: true
        type: string
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Github Pages to gh-pages folder
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm dependency build mailu

      - name: Run helm lint
        run: helm lint --strict --values mailu/ci/helm-lint-values.yaml mailu

      - name: Run helm package
        run: helm package mailu --destination gh-pages

      - name: Run helm repo index
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d "/" -f 2)
          helm repo index gh-pages --url https://${{ github.repository_owner }}.github.io/${REPO_NAME}

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github actions"
          git add .
          git commit -m "New Chart Release for ${{ github.event.inputs.package }}: ${{ github.event.inputs.version }}"
          git push
        working-directory: gh-pages
